- name: setup the rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks: 
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: intall rabbitmq server
    ansible.builtin.package:
      name: rabbitmq
      state: present
    
  - name: start and enable rabbitmq server
    ansible.builtin.service:
      name: rabbitmq
      state: started
      enabled: yes

  - name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    state: present

- name: set permissions for rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
